# include: package:lint/recommended.yaml
# include: package:lint/casual.yaml
include: package:lint/strict.yaml
# language:
#   strict-casts: false
#   strict-inference: false
#   strict-raw-types: false
#   implicit-casts: true
# await_only_futures: true
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
rules:
  - always_declare_return_types
  - cancel_subscriptions
  - close_sinks
  - comment_references
  - one_member_abstracts
  - only_throw_errors
  - package_api_docs
  - prefer_final_in_for_each
  - prefer_single_quotes

# avoid leading underscro to false
# 
