workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      # android_signing:
      groups:
        - keystore_credentials
      #   - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      # vars:
      #   PACKAGE_NAME: "io.codemagic.flutteryaml" # <-- Put your package name here
      #   GOOGLE_PLAY_TRACK: "alpha"
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Set up local.properties
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF    
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      # - name: Flutter analyze
      #   script: |
      #     flutter analyze
      # - name: Flutter unit tests
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name:
          Build AAB with Flutter
          # BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          # flutter build appbundle --release \
          #   --build-name=1.0.$BUILD_NUMBER \
          #   --build-number=$BUILD_NUMBER
        script: |

          flutter build appbundle --obfuscate --split-debug-info=build/bioplus --target=lib/main_prod.dart

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt

    # cache:

    # publishing:
    # email:
    # recipients:
    #   - user_1@example.com
    #   - user_2@example.com
    # notify:
    #   success: true
    #   failure: false
    # google_play:
    #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #   track: $GOOGLE_PLAY_TRACK
    #   submit_as_draft: true
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    # integrations:
    #   app_store_connect: codemagin
    environment:
      # ios_signing:
      #   distribution_type: app_store
      #   bundle_identifier: com.itrakassets.bioplus
      vars:
        APP_STORE_CONNECT_ISSUER_ID: d9def15f-16e9-4b53-a4c4-6abcbda2ff25
        APP_ID: 6444330345 # <-- Put your APP ID here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
            # - keychain initialize
            # - app-store-connect fetch-signing-files "com.itrakassets.bioplus" --type IOS_APP_STORE
            #   --create
            # - keychain add-certificates
            # - xcode-project use-profiles
            # - flutter build ipa --export-options-plist ~/export_options.plist -t main_prod.dart
      # - name: Flutter analyze
      #   script: |
      #     flutter analyze
      # - name: Flutter unit tests
      #   script: |
      #     flutter test
      #   ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --obfuscate --split-debug-info=build/bioplus \
            --target=lib/main_prod.dart \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: Encrypted(Z0FBQUFBQmoyS0NNRlhuMGFhV2ZrQXFPMDlUSWVxaEZUaXl2dzkwMHlCakdSbWpxXzZMU1lZTlB1UGxibUxBc0YtVTVKMm4waUhQTmJJRTI2RWdiMy1vdnZ0YXIyTjZSa251RHNLeDJaenQ3enZfbG02NkVSY2tkeDJ1eDM4eXBNSVNwbjJRUmJuSGpLQkV0UkVJX3E1YUFsYmZYM3NHeVgydXpiYnc4MGw1d3hxSmhuMGM5MWxIZVNiMlUtQ3pXXzNheC1qSjZyMGdJMV9PMERLQjIzaGJEeFgzb0pyeWRKUVlsT1lUclgwMllRVGgxOWlDdkNieUZDaWJxYlNJUEtjYmtESVJ1bU9ZMEkwc09TR1Uxa0tTQmU2TkUtdmZPQzVWUExxeEtsT29TcDBjRVBDdC1TdUtCb3padVprQnA0b21XZTgyLW1GRnhLRFNRYk9ONEgzVjNhdWRYVDF1a3FnY2tiOHhJTDJVdlhaTG0xeHRaUE5VX2Eyb0xyRUxIcVFBVGdNYmVJTHRlU2ljLXFEU0VVSlg2blpDTlhmdTV2bWNqVTJXRm5wRm5VX1FQOHJidVotVT0=)
        key_id: 8Z52QQ4824
        issuer_id: d9def15f-16e9-4b53-a4c4-6abcbda2ff25
        submit_to_testflight: true
        submit_to_app_store: false
      # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails
      slack:
        # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
        channel: "#builds"
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To receive a notification when a build succeeds
          failure: false # To not receive a notification when a build fails


        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        # beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
        #   - group name 1
        #   - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
